# Generated by Django 4.0.4 on 2022-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_likes_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_link',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
